import {
  Container,
  ContainerButton,
  ContainerCalc,
  ContainerCheck,
  ContainerCheckBox,
  ContainerDescription,
  ContainerDetails,
  ContainerDetailsImc,
  ContainerForm,
  ContainerFormLentes,
  ContainerGrau,
  ContainerGrauTop,
  ContainerImc,
  ContainerInput,
  ContainerModalCheckBox,
  ContainerPrescription,
  ContainerSelect,
  ContainerText,
  Label,
  Overlay,
  Select,
  Text,
  TextImc,
  Title
} from './styles';
import { Icon } from '@/components/Icon';
import { useState, useContext } from 'react';
import { Input, SaveAndAdd } from '../styles';
import RichText from '../RichText';
import { PrescricaoDeOculos } from '@/contexts/prescricaoDeOculos';

export default function ComponentPrescricaoDeOculosFinal() {
  const [openModal, setOpenModal] = useState(false);
  const [openModalCheckBox, setOpenModalCheckBox] = useState(false);
  const [openModalSelect, setOpenModalSelect] = useState(false);
  const { closePrescricaoDeOculos } = useContext(PrescricaoDeOculos);

  const handleCloseModal = () => {
    setOpenModal(false);
  };
  const handleOpenModalCheckBox = () => {
    setOpenModalCheckBox(true);
  };
  const handleCloseModalCheckBox = () => {
    setOpenModalCheckBox(false);
  };
  const handleOpenModalSelect = () => {
    setOpenModalSelect(true);
  };
  const handleCloseModalSelect = () => {
    setOpenModalSelect(false);
  };

  return (
    <Container>
      <button className="buttonClose" onClick={() => closePrescricaoDeOculos()}>
        <Icon
          name="closeSelect"
          size={13}
          style={{
            marginTop: '2px'
          }}
        />
      </button>
      <ContainerImc>
        <ContainerText>
          Digite aqui os dados da prescrição de óculos que deseja incluir:
        </ContainerText>
        <Label>
          <Title>Dados</Title>
          <ContainerDescription>
            <TextImc>Para longe</TextImc>
            <ContainerPrescription>
              <ContainerDetailsImc>
                <ContainerCalc>
                  <ContainerInput>
                    <Text>Esférico</Text>
                    <ContainerDetails>
                      O.D.
                      <Input />
                      <button
                        className="buttonOpen"
                        onClick={handleOpenModalSelect}
                      >
                        <Icon
                          name="groupSelect"
                          size={13}
                          style={{
                            marginLeft: '-5px',
                            marginTop: '8px'
                          }}
                        />
                      </button>
                      {openModalSelect && (
                        <Overlay>
                          <ContainerGrauTop>
                            <button
                              className="buttonClose"
                              onClick={handleCloseModalSelect}
                            >
                              <Icon
                                name="closeSelect"
                                size={13}
                                style={{
                                  marginTop: '2px'
                                }}
                              />
                            </button>
                            <ContainerSelect>
                              <p>Selecione um valor: </p>
                              <Select>
                                <button>-15,00</button>
                                <button>-14,75</button>
                                <button>-14,50</button>
                                <button>-14,25</button>
                                <button>-14,00</button>
                                <button>-13,75</button>
                                <button>-13,50</button>
                                <button>-13,25</button>
                                <button>-13,00</button>
                                <button>-12,75</button>
                                <button>-12,50</button>
                                <button>-12,25</button>
                                <button>-12,00</button>
                                <button>-11,75</button>
                                <button>-11,50</button>
                                <button>-11,25</button>
                                <button>-11,00</button>
                                <button>-10,00</button>
                                <button>-10,75</button>
                                <button>-10,50</button>
                                <button>-10,25</button>
                                <button>-10,00</button>
                                <button>-9,75</button>
                                <button>-9,50</button>
                                <button>-9,25</button>
                                <button>-9,00</button>
                                <button>-8,00</button>
                                <button>-8,75</button>
                                <button>-8,50</button>
                                <button>-8,25</button>
                                <button>-8,00</button>
                                <button>-7,75</button>
                                <button>-7,50</button>
                                <button>-7,25</button>
                                <button>-7,00</button>
                                <button>-6,75</button>
                                <button>-6,50</button>
                                <button>-6,25</button>
                                <button>-6,00</button>
                                <button>-5,75</button>
                                <button>-5,50</button>
                                <button>-5,25</button>
                                <button>-5,00</button>
                                <button>-4,75</button>
                                <button>-4,50</button>
                                <button>-4,25</button>
                                <button>-4,00</button>
                                <button>-3,75</button>
                                <button>-3,50</button>
                                <button>-3,25</button>
                                <button>-3,00</button>
                                <button>-2,75</button>
                                <button>-2,50</button>
                                <button>-2,25</button>
                                <button>-2,00</button>
                                <button>-1,75</button>
                                <button>-1,50</button>
                                <button>-1,25</button>
                                <button>-1,00</button>
                                <button>-0,75</button>
                                <button>-0,50</button>
                                <button>-0,25</button>
                                <button>Plano</button>
                                <button>+0,25</button>
                                <button>+0,50</button>
                                <button>+0,75</button>
                                <button>+1,00</button>
                                <button>+1,25</button>
                                <button>+1,50</button>
                                <button>+1,75</button>
                                <button>+2,00</button>
                                <button>+2,25</button>
                                <button>+2,50</button>
                                <button>+2,75</button>
                                <button>+3,00</button>
                                <button>+3,25</button>
                                <button>+3,50</button>
                                <button>+3,75</button>
                                <button>+4,00</button>
                                <button>+4,25</button>
                                <button>+4,50</button>
                                <button>+4,75</button>
                                <button>+5,00</button>
                                <button>+5,25</button>
                                <button>+5,50</button>
                                <button>+5,75</button>
                                <button>+6,00</button>
                                <button>+6,25</button>
                                <button>+6,50</button>
                                <button>+6,75</button>
                                <button>+7,00</button>
                                <button>+7,25</button>
                                <button>+7,50</button>
                                <button>+7,75</button>
                                <button>+8,00</button>
                                <button>+8,25</button>
                                <button>+8,50</button>
                                <button>+8,75</button>
                                <button>+9,00</button>
                                <button>+9,25</button>
                                <button>+9,50</button>
                                <button>+9,75</button>
                                <button>+10,00</button>
                                <button>+10,25</button>
                                <button>+10,50</button>
                                <button>+10,75</button>
                                <button>+11,00</button>
                                <button>+11,25</button>
                                <button>+11,50</button>
                                <button>+11,75</button>
                                <button>+12,00</button>
                                <button>+12,25</button>
                                <button>+12,50</button>
                                <button>+12,75</button>
                                <button>+13,00</button>
                                <button>+13,25</button>
                                <button>+13,50</button>
                                <button>+13,75</button>
                                <button>+14,00</button>
                                <button>+14,25</button>
                                <button>+14,50</button>
                                <button>+14,75</button>
                                <button>+15,00</button>
                                <button>+15,25</button>
                                <button>+15,50</button>
                                <button>+15,75</button>
                              </Select>
                            </ContainerSelect>
                          </ContainerGrauTop>
                        </Overlay>
                      )}
                    </ContainerDetails>
                  </ContainerInput>
                  <ContainerInput>
                    <Text>Cilíndrico</Text>
                    <ContainerDetails>
                      <Input />
                      <button
                        className="buttonOpen"
                        onClick={handleOpenModalSelect}
                      >
                        <Icon
                          name="groupSelect"
                          size={13}
                          style={{
                            marginLeft: '-5px',
                            marginTop: '8px'
                          }}
                        />
                      </button>

                      {openModalSelect && (
                        <Overlay>
                          <ContainerGrauTop>
                            <button
                              className="buttonClose"
                              onClick={handleCloseModalSelect}
                            >
                              <Icon
                                name="closeSelect"
                                size={13}
                                style={{
                                  marginTop: '2px'
                                }}
                              />
                            </button>
                            <ContainerSelect>
                              <p>Selecione um valor: </p>
                              <Select>
                                <button>-15,00</button>
                                <button>-14,75</button>
                                <button>-14,50</button>
                                <button>-14,25</button>
                                <button>-14,00</button>
                                <button>-13,75</button>
                                <button>-13,50</button>
                                <button>-13,25</button>
                                <button>-13,00</button>
                                <button>-12,75</button>
                                <button>-12,50</button>
                                <button>-12,25</button>
                                <button>-12,00</button>
                                <button>-11,75</button>
                                <button>-11,50</button>
                                <button>-11,25</button>
                                <button>-11,00</button>
                                <button>-10,00</button>
                                <button>-10,75</button>
                                <button>-10,50</button>
                                <button>-10,25</button>
                                <button>-10,00</button>
                                <button>-9,75</button>
                                <button>-9,50</button>
                                <button>-9,25</button>
                                <button>-9,00</button>
                                <button>-8,00</button>
                                <button>-8,75</button>
                                <button>-8,50</button>
                                <button>-8,25</button>
                                <button>-8,00</button>
                                <button>-7,75</button>
                                <button>-7,50</button>
                                <button>-7,25</button>
                                <button>-7,00</button>
                                <button>-6,75</button>
                                <button>-6,50</button>
                                <button>-6,25</button>
                                <button>-6,00</button>
                                <button>-5,75</button>
                                <button>-5,50</button>
                                <button>-5,25</button>
                                <button>-5,00</button>
                                <button>-4,75</button>
                                <button>-4,50</button>
                                <button>-4,25</button>
                                <button>-4,00</button>
                                <button>-3,75</button>
                                <button>-3,50</button>
                                <button>-3,25</button>
                                <button>-3,00</button>
                                <button>-2,75</button>
                                <button>-2,50</button>
                                <button>-2,25</button>
                                <button>-2,00</button>
                                <button>-1,75</button>
                                <button>-1,50</button>
                                <button>-1,25</button>
                                <button>-1,00</button>
                                <button>-0,75</button>
                                <button>-0,50</button>
                                <button>-0,25</button>
                                <button>Plano</button>
                                <button>+0,25</button>
                                <button>+0,50</button>
                                <button>+0,75</button>
                                <button>+1,00</button>
                                <button>+1,25</button>
                                <button>+1,50</button>
                                <button>+1,75</button>
                                <button>+2,00</button>
                                <button>+2,25</button>
                                <button>+2,50</button>
                                <button>+2,75</button>
                                <button>+3,00</button>
                                <button>+3,25</button>
                                <button>+3,50</button>
                                <button>+3,75</button>
                                <button>+4,00</button>
                                <button>+4,25</button>
                                <button>+4,50</button>
                                <button>+4,75</button>
                                <button>+5,00</button>
                                <button>+5,25</button>
                                <button>+5,50</button>
                                <button>+5,75</button>
                                <button>+6,00</button>
                                <button>+6,25</button>
                                <button>+6,50</button>
                                <button>+6,75</button>
                                <button>+7,00</button>
                                <button>+7,25</button>
                                <button>+7,50</button>
                                <button>+7,75</button>
                                <button>+8,00</button>
                                <button>+8,25</button>
                                <button>+8,50</button>
                                <button>+8,75</button>
                                <button>+9,00</button>
                                <button>+9,25</button>
                                <button>+9,50</button>
                                <button>+9,75</button>
                                <button>+10,00</button>
                                <button>+10,25</button>
                                <button>+10,50</button>
                                <button>+10,75</button>
                                <button>+11,00</button>
                                <button>+11,25</button>
                                <button>+11,50</button>
                                <button>+11,75</button>
                                <button>+12,00</button>
                                <button>+12,25</button>
                                <button>+12,50</button>
                                <button>+12,75</button>
                                <button>+13,00</button>
                                <button>+13,25</button>
                                <button>+13,50</button>
                                <button>+13,75</button>
                                <button>+14,00</button>
                                <button>+14,25</button>
                                <button>+14,50</button>
                                <button>+14,75</button>
                                <button>+15,00</button>
                                <button>+15,25</button>
                                <button>+15,50</button>
                                <button>+15,75</button>
                              </Select>
                            </ContainerSelect>
                          </ContainerGrauTop>
                        </Overlay>
                      )}
                    </ContainerDetails>
                  </ContainerInput>
                  <ContainerInput>
                    <Text>Eixo</Text>
                    <ContainerDetails>
                      <Input />
                      <ContainerGrau>º</ContainerGrau>
                    </ContainerDetails>
                  </ContainerInput>
                  <ContainerInput>
                    <Text>DNP</Text>
                    <ContainerDetails>
                      <Input />
                      mm
                    </ContainerDetails>
                  </ContainerInput>
                </ContainerCalc>
              </ContainerDetailsImc>
              <ContainerDetailsImc>
                <ContainerCalc>
                  <ContainerInput>
                    <ContainerDetails>
                      O.E.
                      <Input />
                      <button
                        className="buttonOpen"
                        onClick={handleOpenModalSelect}
                      >
                        <Icon
                          name="groupSelect"
                          size={13}
                          style={{
                            marginLeft: '-5px',
                            marginTop: '8px'
                          }}
                        />
                      </button>
                      {openModalSelect && (
                        <Overlay>
                          <ContainerGrauTop>
                            <button
                              className="buttonClose"
                              onClick={handleCloseModalSelect}
                            >
                              <Icon
                                name="closeSelect"
                                size={13}
                                style={{
                                  marginTop: '2px'
                                }}
                              />
                            </button>
                            <ContainerSelect>
                              <p>Selecione um valor: </p>
                              <Select>
                                <button>-15,00</button>
                                <button>-14,75</button>
                                <button>-14,50</button>
                                <button>-14,25</button>
                                <button>-14,00</button>
                                <button>-13,75</button>
                                <button>-13,50</button>
                                <button>-13,25</button>
                                <button>-13,00</button>
                                <button>-12,75</button>
                                <button>-12,50</button>
                                <button>-12,25</button>
                                <button>-12,00</button>
                                <button>-11,75</button>
                                <button>-11,50</button>
                                <button>-11,25</button>
                                <button>-11,00</button>
                                <button>-10,00</button>
                                <button>-10,75</button>
                                <button>-10,50</button>
                                <button>-10,25</button>
                                <button>-10,00</button>
                                <button>-9,75</button>
                                <button>-9,50</button>
                                <button>-9,25</button>
                                <button>-9,00</button>
                                <button>-8,00</button>
                                <button>-8,75</button>
                                <button>-8,50</button>
                                <button>-8,25</button>
                                <button>-8,00</button>
                                <button>-7,75</button>
                                <button>-7,50</button>
                                <button>-7,25</button>
                                <button>-7,00</button>
                                <button>-6,75</button>
                                <button>-6,50</button>
                                <button>-6,25</button>
                                <button>-6,00</button>
                                <button>-5,75</button>
                                <button>-5,50</button>
                                <button>-5,25</button>
                                <button>-5,00</button>
                                <button>-4,75</button>
                                <button>-4,50</button>
                                <button>-4,25</button>
                                <button>-4,00</button>
                                <button>-3,75</button>
                                <button>-3,50</button>
                                <button>-3,25</button>
                                <button>-3,00</button>
                                <button>-2,75</button>
                                <button>-2,50</button>
                                <button>-2,25</button>
                                <button>-2,00</button>
                                <button>-1,75</button>
                                <button>-1,50</button>
                                <button>-1,25</button>
                                <button>-1,00</button>
                                <button>-0,75</button>
                                <button>-0,50</button>
                                <button>-0,25</button>
                                <button>Plano</button>
                                <button>+0,25</button>
                                <button>+0,50</button>
                                <button>+0,75</button>
                                <button>+1,00</button>
                                <button>+1,25</button>
                                <button>+1,50</button>
                                <button>+1,75</button>
                                <button>+2,00</button>
                                <button>+2,25</button>
                                <button>+2,50</button>
                                <button>+2,75</button>
                                <button>+3,00</button>
                                <button>+3,25</button>
                                <button>+3,50</button>
                                <button>+3,75</button>
                                <button>+4,00</button>
                                <button>+4,25</button>
                                <button>+4,50</button>
                                <button>+4,75</button>
                                <button>+5,00</button>
                                <button>+5,25</button>
                                <button>+5,50</button>
                                <button>+5,75</button>
                                <button>+6,00</button>
                                <button>+6,25</button>
                                <button>+6,50</button>
                                <button>+6,75</button>
                                <button>+7,00</button>
                                <button>+7,25</button>
                                <button>+7,50</button>
                                <button>+7,75</button>
                                <button>+8,00</button>
                                <button>+8,25</button>
                                <button>+8,50</button>
                                <button>+8,75</button>
                                <button>+9,00</button>
                                <button>+9,25</button>
                                <button>+9,50</button>
                                <button>+9,75</button>
                                <button>+10,00</button>
                                <button>+10,25</button>
                                <button>+10,50</button>
                                <button>+10,75</button>
                                <button>+11,00</button>
                                <button>+11,25</button>
                                <button>+11,50</button>
                                <button>+11,75</button>
                                <button>+12,00</button>
                                <button>+12,25</button>
                                <button>+12,50</button>
                                <button>+12,75</button>
                                <button>+13,00</button>
                                <button>+13,25</button>
                                <button>+13,50</button>
                                <button>+13,75</button>
                                <button>+14,00</button>
                                <button>+14,25</button>
                                <button>+14,50</button>
                                <button>+14,75</button>
                                <button>+15,00</button>
                                <button>+15,25</button>
                                <button>+15,50</button>
                                <button>+15,75</button>
                              </Select>
                            </ContainerSelect>
                          </ContainerGrauTop>
                        </Overlay>
                      )}
                    </ContainerDetails>
                  </ContainerInput>
                  <ContainerInput>
                    <ContainerDetails>
                      <Input />
                      <button
                        className="buttonOpen"
                        onClick={handleOpenModalSelect}
                      >
                        <Icon
                          name="groupSelect"
                          size={13}
                          style={{
                            marginLeft: '-5px',
                            marginTop: '8px'
                          }}
                        />
                      </button>
                      {openModalSelect && (
                        <Overlay>
                          <ContainerGrauTop>
                            <button
                              className="buttonClose"
                              onClick={handleCloseModalSelect}
                            >
                              <Icon
                                name="closeSelect"
                                size={13}
                                style={{
                                  marginTop: '2px'
                                }}
                              />
                            </button>
                            <ContainerSelect>
                              <p>Selecione um valor: </p>
                              <Select>
                                <button>-15,00</button>
                                <button>-14,75</button>
                                <button>-14,50</button>
                                <button>-14,25</button>
                                <button>-14,00</button>
                                <button>-13,75</button>
                                <button>-13,50</button>
                                <button>-13,25</button>
                                <button>-13,00</button>
                                <button>-12,75</button>
                                <button>-12,50</button>
                                <button>-12,25</button>
                                <button>-12,00</button>
                                <button>-11,75</button>
                                <button>-11,50</button>
                                <button>-11,25</button>
                                <button>-11,00</button>
                                <button>-10,00</button>
                                <button>-10,75</button>
                                <button>-10,50</button>
                                <button>-10,25</button>
                                <button>-10,00</button>
                                <button>-9,75</button>
                                <button>-9,50</button>
                                <button>-9,25</button>
                                <button>-9,00</button>
                                <button>-8,00</button>
                                <button>-8,75</button>
                                <button>-8,50</button>
                                <button>-8,25</button>
                                <button>-8,00</button>
                                <button>-7,75</button>
                                <button>-7,50</button>
                                <button>-7,25</button>
                                <button>-7,00</button>
                                <button>-6,75</button>
                                <button>-6,50</button>
                                <button>-6,25</button>
                                <button>-6,00</button>
                                <button>-5,75</button>
                                <button>-5,50</button>
                                <button>-5,25</button>
                                <button>-5,00</button>
                                <button>-4,75</button>
                                <button>-4,50</button>
                                <button>-4,25</button>
                                <button>-4,00</button>
                                <button>-3,75</button>
                                <button>-3,50</button>
                                <button>-3,25</button>
                                <button>-3,00</button>
                                <button>-2,75</button>
                                <button>-2,50</button>
                                <button>-2,25</button>
                                <button>-2,00</button>
                                <button>-1,75</button>
                                <button>-1,50</button>
                                <button>-1,25</button>
                                <button>-1,00</button>
                                <button>-0,75</button>
                                <button>-0,50</button>
                                <button>-0,25</button>
                                <button>Plano</button>
                                <button>+0,25</button>
                                <button>+0,50</button>
                                <button>+0,75</button>
                                <button>+1,00</button>
                                <button>+1,25</button>
                                <button>+1,50</button>
                                <button>+1,75</button>
                                <button>+2,00</button>
                                <button>+2,25</button>
                                <button>+2,50</button>
                                <button>+2,75</button>
                                <button>+3,00</button>
                                <button>+3,25</button>
                                <button>+3,50</button>
                                <button>+3,75</button>
                                <button>+4,00</button>
                                <button>+4,25</button>
                                <button>+4,50</button>
                                <button>+4,75</button>
                                <button>+5,00</button>
                                <button>+5,25</button>
                                <button>+5,50</button>
                                <button>+5,75</button>
                                <button>+6,00</button>
                                <button>+6,25</button>
                                <button>+6,50</button>
                                <button>+6,75</button>
                                <button>+7,00</button>
                                <button>+7,25</button>
                                <button>+7,50</button>
                                <button>+7,75</button>
                                <button>+8,00</button>
                                <button>+8,25</button>
                                <button>+8,50</button>
                                <button>+8,75</button>
                                <button>+9,00</button>
                                <button>+9,25</button>
                                <button>+9,50</button>
                                <button>+9,75</button>
                                <button>+10,00</button>
                                <button>+10,25</button>
                                <button>+10,50</button>
                                <button>+10,75</button>
                                <button>+11,00</button>
                                <button>+11,25</button>
                                <button>+11,50</button>
                                <button>+11,75</button>
                                <button>+12,00</button>
                                <button>+12,25</button>
                                <button>+12,50</button>
                                <button>+12,75</button>
                                <button>+13,00</button>
                                <button>+13,25</button>
                                <button>+13,50</button>
                                <button>+13,75</button>
                                <button>+14,00</button>
                                <button>+14,25</button>
                                <button>+14,50</button>
                                <button>+14,75</button>
                                <button>+15,00</button>
                                <button>+15,25</button>
                                <button>+15,50</button>
                                <button>+15,75</button>
                              </Select>
                            </ContainerSelect>
                          </ContainerGrauTop>
                        </Overlay>
                      )}
                    </ContainerDetails>
                  </ContainerInput>
                  <ContainerInput>
                    <ContainerDetails>
                      <Input />
                      <ContainerGrau>º</ContainerGrau>
                    </ContainerDetails>
                  </ContainerInput>
                  <ContainerInput>
                    <ContainerDetails>
                      <Input />
                      mm
                    </ContainerDetails>
                  </ContainerInput>
                </ContainerCalc>
              </ContainerDetailsImc>
            </ContainerPrescription>
          </ContainerDescription>
          <ContainerDetailsImc>
            <TextImc style={{ marginRight: '70px' }}>Adição</TextImc>
            <ContainerCalc>
              <ContainerInput>
                <ContainerDetails>
                  <Input placeholder="0,00" />
                </ContainerDetails>
              </ContainerInput>
            </ContainerCalc>
          </ContainerDetailsImc>

          <hr
            style={{
              border: '1px solid grey',
              display: 'flex',
              width: '100%',
              marginTop: '10px',
              marginBottom: '10px'
            }}
          />
          <ContainerDescription>
            <TextImc>Para longe</TextImc>
            <ContainerPrescription>
              <ContainerDetailsImc>
                <ContainerCalc>
                  <ContainerInput>
                    <Text>Esférico</Text>
                    <ContainerDetails>
                      O.D.
                      <Input />
                      <button
                        className="buttonOpen"
                        onClick={handleOpenModalSelect}
                      >
                        <Icon
                          name="groupSelect"
                          size={13}
                          style={{
                            marginLeft: '-5px',
                            marginTop: '8px'
                          }}
                        />
                      </button>
                      {openModalSelect && (
                        <Overlay>
                          <ContainerGrauTop>
                            <button
                              className="buttonClose"
                              onClick={handleCloseModalSelect}
                            >
                              <Icon
                                name="closeSelect"
                                size={13}
                                style={{
                                  marginTop: '2px'
                                }}
                              />
                            </button>
                            <ContainerSelect>
                              <p>Selecione um valor: </p>
                              <Select>
                                <button>-15,00</button>
                                <button>-14,75</button>
                                <button>-14,50</button>
                                <button>-14,25</button>
                                <button>-14,00</button>
                                <button>-13,75</button>
                                <button>-13,50</button>
                                <button>-13,25</button>
                                <button>-13,00</button>
                                <button>-12,75</button>
                                <button>-12,50</button>
                                <button>-12,25</button>
                                <button>-12,00</button>
                                <button>-11,75</button>
                                <button>-11,50</button>
                                <button>-11,25</button>
                                <button>-11,00</button>
                                <button>-10,00</button>
                                <button>-10,75</button>
                                <button>-10,50</button>
                                <button>-10,25</button>
                                <button>-10,00</button>
                                <button>-9,75</button>
                                <button>-9,50</button>
                                <button>-9,25</button>
                                <button>-9,00</button>
                                <button>-8,00</button>
                                <button>-8,75</button>
                                <button>-8,50</button>
                                <button>-8,25</button>
                                <button>-8,00</button>
                                <button>-7,75</button>
                                <button>-7,50</button>
                                <button>-7,25</button>
                                <button>-7,00</button>
                                <button>-6,75</button>
                                <button>-6,50</button>
                                <button>-6,25</button>
                                <button>-6,00</button>
                                <button>-5,75</button>
                                <button>-5,50</button>
                                <button>-5,25</button>
                                <button>-5,00</button>
                                <button>-4,75</button>
                                <button>-4,50</button>
                                <button>-4,25</button>
                                <button>-4,00</button>
                                <button>-3,75</button>
                                <button>-3,50</button>
                                <button>-3,25</button>
                                <button>-3,00</button>
                                <button>-2,75</button>
                                <button>-2,50</button>
                                <button>-2,25</button>
                                <button>-2,00</button>
                                <button>-1,75</button>
                                <button>-1,50</button>
                                <button>-1,25</button>
                                <button>-1,00</button>
                                <button>-0,75</button>
                                <button>-0,50</button>
                                <button>-0,25</button>
                                <button>Plano</button>
                                <button>+0,25</button>
                                <button>+0,50</button>
                                <button>+0,75</button>
                                <button>+1,00</button>
                                <button>+1,25</button>
                                <button>+1,50</button>
                                <button>+1,75</button>
                                <button>+2,00</button>
                                <button>+2,25</button>
                                <button>+2,50</button>
                                <button>+2,75</button>
                                <button>+3,00</button>
                                <button>+3,25</button>
                                <button>+3,50</button>
                                <button>+3,75</button>
                                <button>+4,00</button>
                                <button>+4,25</button>
                                <button>+4,50</button>
                                <button>+4,75</button>
                                <button>+5,00</button>
                                <button>+5,25</button>
                                <button>+5,50</button>
                                <button>+5,75</button>
                                <button>+6,00</button>
                                <button>+6,25</button>
                                <button>+6,50</button>
                                <button>+6,75</button>
                                <button>+7,00</button>
                                <button>+7,25</button>
                                <button>+7,50</button>
                                <button>+7,75</button>
                                <button>+8,00</button>
                                <button>+8,25</button>
                                <button>+8,50</button>
                                <button>+8,75</button>
                                <button>+9,00</button>
                                <button>+9,25</button>
                                <button>+9,50</button>
                                <button>+9,75</button>
                                <button>+10,00</button>
                                <button>+10,25</button>
                                <button>+10,50</button>
                                <button>+10,75</button>
                                <button>+11,00</button>
                                <button>+11,25</button>
                                <button>+11,50</button>
                                <button>+11,75</button>
                                <button>+12,00</button>
                                <button>+12,25</button>
                                <button>+12,50</button>
                                <button>+12,75</button>
                                <button>+13,00</button>
                                <button>+13,25</button>
                                <button>+13,50</button>
                                <button>+13,75</button>
                                <button>+14,00</button>
                                <button>+14,25</button>
                                <button>+14,50</button>
                                <button>+14,75</button>
                                <button>+15,00</button>
                                <button>+15,25</button>
                                <button>+15,50</button>
                                <button>+15,75</button>
                              </Select>
                            </ContainerSelect>
                          </ContainerGrauTop>
                        </Overlay>
                      )}
                    </ContainerDetails>
                  </ContainerInput>
                  <ContainerInput>
                    <Text>Cilíndrico</Text>
                    <ContainerDetails>
                      <Input />
                      <button
                        className="buttonOpen"
                        onClick={handleOpenModalSelect}
                      >
                        <Icon
                          name="groupSelect"
                          size={13}
                          style={{
                            marginLeft: '-5px',
                            marginTop: '8px'
                          }}
                        />
                      </button>

                      {openModalSelect && (
                        <Overlay>
                          <ContainerGrauTop>
                            <button
                              className="buttonClose"
                              onClick={handleCloseModalSelect}
                            >
                              <Icon
                                name="closeSelect"
                                size={13}
                                style={{
                                  marginTop: '2px'
                                }}
                              />
                            </button>
                            <ContainerSelect>
                              <p>Selecione um valor: </p>
                              <Select>
                                <button>-15,00</button>
                                <button>-14,75</button>
                                <button>-14,50</button>
                                <button>-14,25</button>
                                <button>-14,00</button>
                                <button>-13,75</button>
                                <button>-13,50</button>
                                <button>-13,25</button>
                                <button>-13,00</button>
                                <button>-12,75</button>
                                <button>-12,50</button>
                                <button>-12,25</button>
                                <button>-12,00</button>
                                <button>-11,75</button>
                                <button>-11,50</button>
                                <button>-11,25</button>
                                <button>-11,00</button>
                                <button>-10,00</button>
                                <button>-10,75</button>
                                <button>-10,50</button>
                                <button>-10,25</button>
                                <button>-10,00</button>
                                <button>-9,75</button>
                                <button>-9,50</button>
                                <button>-9,25</button>
                                <button>-9,00</button>
                                <button>-8,00</button>
                                <button>-8,75</button>
                                <button>-8,50</button>
                                <button>-8,25</button>
                                <button>-8,00</button>
                                <button>-7,75</button>
                                <button>-7,50</button>
                                <button>-7,25</button>
                                <button>-7,00</button>
                                <button>-6,75</button>
                                <button>-6,50</button>
                                <button>-6,25</button>
                                <button>-6,00</button>
                                <button>-5,75</button>
                                <button>-5,50</button>
                                <button>-5,25</button>
                                <button>-5,00</button>
                                <button>-4,75</button>
                                <button>-4,50</button>
                                <button>-4,25</button>
                                <button>-4,00</button>
                                <button>-3,75</button>
                                <button>-3,50</button>
                                <button>-3,25</button>
                                <button>-3,00</button>
                                <button>-2,75</button>
                                <button>-2,50</button>
                                <button>-2,25</button>
                                <button>-2,00</button>
                                <button>-1,75</button>
                                <button>-1,50</button>
                                <button>-1,25</button>
                                <button>-1,00</button>
                                <button>-0,75</button>
                                <button>-0,50</button>
                                <button>-0,25</button>
                                <button>Plano</button>
                                <button>+0,25</button>
                                <button>+0,50</button>
                                <button>+0,75</button>
                                <button>+1,00</button>
                                <button>+1,25</button>
                                <button>+1,50</button>
                                <button>+1,75</button>
                                <button>+2,00</button>
                                <button>+2,25</button>
                                <button>+2,50</button>
                                <button>+2,75</button>
                                <button>+3,00</button>
                                <button>+3,25</button>
                                <button>+3,50</button>
                                <button>+3,75</button>
                                <button>+4,00</button>
                                <button>+4,25</button>
                                <button>+4,50</button>
                                <button>+4,75</button>
                                <button>+5,00</button>
                                <button>+5,25</button>
                                <button>+5,50</button>
                                <button>+5,75</button>
                                <button>+6,00</button>
                                <button>+6,25</button>
                                <button>+6,50</button>
                                <button>+6,75</button>
                                <button>+7,00</button>
                                <button>+7,25</button>
                                <button>+7,50</button>
                                <button>+7,75</button>
                                <button>+8,00</button>
                                <button>+8,25</button>
                                <button>+8,50</button>
                                <button>+8,75</button>
                                <button>+9,00</button>
                                <button>+9,25</button>
                                <button>+9,50</button>
                                <button>+9,75</button>
                                <button>+10,00</button>
                                <button>+10,25</button>
                                <button>+10,50</button>
                                <button>+10,75</button>
                                <button>+11,00</button>
                                <button>+11,25</button>
                                <button>+11,50</button>
                                <button>+11,75</button>
                                <button>+12,00</button>
                                <button>+12,25</button>
                                <button>+12,50</button>
                                <button>+12,75</button>
                                <button>+13,00</button>
                                <button>+13,25</button>
                                <button>+13,50</button>
                                <button>+13,75</button>
                                <button>+14,00</button>
                                <button>+14,25</button>
                                <button>+14,50</button>
                                <button>+14,75</button>
                                <button>+15,00</button>
                                <button>+15,25</button>
                                <button>+15,50</button>
                                <button>+15,75</button>
                              </Select>
                            </ContainerSelect>
                          </ContainerGrauTop>
                        </Overlay>
                      )}
                    </ContainerDetails>
                  </ContainerInput>
                  <ContainerInput>
                    <Text>Eixo</Text>
                    <ContainerDetails>
                      <Input />
                      <ContainerGrau>º</ContainerGrau>
                    </ContainerDetails>
                  </ContainerInput>
                  <ContainerInput>
                    <Text>DNP</Text>
                    <ContainerDetails>
                      <Input />
                      mm
                    </ContainerDetails>
                  </ContainerInput>
                </ContainerCalc>
              </ContainerDetailsImc>
              <ContainerDetailsImc>
                <ContainerCalc>
                  <ContainerInput>
                    <ContainerDetails>
                      O.E.
                      <Input />
                      <button
                        className="buttonOpen"
                        onClick={handleOpenModalSelect}
                      >
                        <Icon
                          name="groupSelect"
                          size={13}
                          style={{
                            marginLeft: '-5px',
                            marginTop: '8px'
                          }}
                        />
                      </button>
                      {openModalSelect && (
                        <Overlay>
                          <ContainerGrauTop>
                            <button
                              className="buttonClose"
                              onClick={handleCloseModalSelect}
                            >
                              <Icon
                                name="closeSelect"
                                size={13}
                                style={{
                                  marginTop: '2px'
                                }}
                              />
                            </button>
                            <ContainerSelect>
                              <p>Selecione um valor: </p>
                              <Select>
                                <button>-15,00</button>
                                <button>-14,75</button>
                                <button>-14,50</button>
                                <button>-14,25</button>
                                <button>-14,00</button>
                                <button>-13,75</button>
                                <button>-13,50</button>
                                <button>-13,25</button>
                                <button>-13,00</button>
                                <button>-12,75</button>
                                <button>-12,50</button>
                                <button>-12,25</button>
                                <button>-12,00</button>
                                <button>-11,75</button>
                                <button>-11,50</button>
                                <button>-11,25</button>
                                <button>-11,00</button>
                                <button>-10,00</button>
                                <button>-10,75</button>
                                <button>-10,50</button>
                                <button>-10,25</button>
                                <button>-10,00</button>
                                <button>-9,75</button>
                                <button>-9,50</button>
                                <button>-9,25</button>
                                <button>-9,00</button>
                                <button>-8,00</button>
                                <button>-8,75</button>
                                <button>-8,50</button>
                                <button>-8,25</button>
                                <button>-8,00</button>
                                <button>-7,75</button>
                                <button>-7,50</button>
                                <button>-7,25</button>
                                <button>-7,00</button>
                                <button>-6,75</button>
                                <button>-6,50</button>
                                <button>-6,25</button>
                                <button>-6,00</button>
                                <button>-5,75</button>
                                <button>-5,50</button>
                                <button>-5,25</button>
                                <button>-5,00</button>
                                <button>-4,75</button>
                                <button>-4,50</button>
                                <button>-4,25</button>
                                <button>-4,00</button>
                                <button>-3,75</button>
                                <button>-3,50</button>
                                <button>-3,25</button>
                                <button>-3,00</button>
                                <button>-2,75</button>
                                <button>-2,50</button>
                                <button>-2,25</button>
                                <button>-2,00</button>
                                <button>-1,75</button>
                                <button>-1,50</button>
                                <button>-1,25</button>
                                <button>-1,00</button>
                                <button>-0,75</button>
                                <button>-0,50</button>
                                <button>-0,25</button>
                                <button>Plano</button>
                                <button>+0,25</button>
                                <button>+0,50</button>
                                <button>+0,75</button>
                                <button>+1,00</button>
                                <button>+1,25</button>
                                <button>+1,50</button>
                                <button>+1,75</button>
                                <button>+2,00</button>
                                <button>+2,25</button>
                                <button>+2,50</button>
                                <button>+2,75</button>
                                <button>+3,00</button>
                                <button>+3,25</button>
                                <button>+3,50</button>
                                <button>+3,75</button>
                                <button>+4,00</button>
                                <button>+4,25</button>
                                <button>+4,50</button>
                                <button>+4,75</button>
                                <button>+5,00</button>
                                <button>+5,25</button>
                                <button>+5,50</button>
                                <button>+5,75</button>
                                <button>+6,00</button>
                                <button>+6,25</button>
                                <button>+6,50</button>
                                <button>+6,75</button>
                                <button>+7,00</button>
                                <button>+7,25</button>
                                <button>+7,50</button>
                                <button>+7,75</button>
                                <button>+8,00</button>
                                <button>+8,25</button>
                                <button>+8,50</button>
                                <button>+8,75</button>
                                <button>+9,00</button>
                                <button>+9,25</button>
                                <button>+9,50</button>
                                <button>+9,75</button>
                                <button>+10,00</button>
                                <button>+10,25</button>
                                <button>+10,50</button>
                                <button>+10,75</button>
                                <button>+11,00</button>
                                <button>+11,25</button>
                                <button>+11,50</button>
                                <button>+11,75</button>
                                <button>+12,00</button>
                                <button>+12,25</button>
                                <button>+12,50</button>
                                <button>+12,75</button>
                                <button>+13,00</button>
                                <button>+13,25</button>
                                <button>+13,50</button>
                                <button>+13,75</button>
                                <button>+14,00</button>
                                <button>+14,25</button>
                                <button>+14,50</button>
                                <button>+14,75</button>
                                <button>+15,00</button>
                                <button>+15,25</button>
                                <button>+15,50</button>
                                <button>+15,75</button>
                              </Select>
                            </ContainerSelect>
                          </ContainerGrauTop>
                        </Overlay>
                      )}
                    </ContainerDetails>
                  </ContainerInput>
                  <ContainerInput>
                    <ContainerDetails>
                      <Input />
                      <button
                        className="buttonOpen"
                        onClick={handleOpenModalSelect}
                      >
                        <Icon
                          name="groupSelect"
                          size={13}
                          style={{
                            marginLeft: '-5px',
                            marginTop: '8px'
                          }}
                        />
                      </button>
                      {openModalSelect && (
                        <Overlay>
                          <ContainerGrauTop>
                            <button
                              className="buttonClose"
                              onClick={handleCloseModalSelect}
                            >
                              <Icon
                                name="closeSelect"
                                size={13}
                                style={{
                                  marginTop: '2px'
                                }}
                              />
                            </button>
                            <ContainerSelect>
                              <p>Selecione um valor: </p>
                              <Select>
                                <button>-15,00</button>
                                <button>-14,75</button>
                                <button>-14,50</button>
                                <button>-14,25</button>
                                <button>-14,00</button>
                                <button>-13,75</button>
                                <button>-13,50</button>
                                <button>-13,25</button>
                                <button>-13,00</button>
                                <button>-12,75</button>
                                <button>-12,50</button>
                                <button>-12,25</button>
                                <button>-12,00</button>
                                <button>-11,75</button>
                                <button>-11,50</button>
                                <button>-11,25</button>
                                <button>-11,00</button>
                                <button>-10,00</button>
                                <button>-10,75</button>
                                <button>-10,50</button>
                                <button>-10,25</button>
                                <button>-10,00</button>
                                <button>-9,75</button>
                                <button>-9,50</button>
                                <button>-9,25</button>
                                <button>-9,00</button>
                                <button>-8,00</button>
                                <button>-8,75</button>
                                <button>-8,50</button>
                                <button>-8,25</button>
                                <button>-8,00</button>
                                <button>-7,75</button>
                                <button>-7,50</button>
                                <button>-7,25</button>
                                <button>-7,00</button>
                                <button>-6,75</button>
                                <button>-6,50</button>
                                <button>-6,25</button>
                                <button>-6,00</button>
                                <button>-5,75</button>
                                <button>-5,50</button>
                                <button>-5,25</button>
                                <button>-5,00</button>
                                <button>-4,75</button>
                                <button>-4,50</button>
                                <button>-4,25</button>
                                <button>-4,00</button>
                                <button>-3,75</button>
                                <button>-3,50</button>
                                <button>-3,25</button>
                                <button>-3,00</button>
                                <button>-2,75</button>
                                <button>-2,50</button>
                                <button>-2,25</button>
                                <button>-2,00</button>
                                <button>-1,75</button>
                                <button>-1,50</button>
                                <button>-1,25</button>
                                <button>-1,00</button>
                                <button>-0,75</button>
                                <button>-0,50</button>
                                <button>-0,25</button>
                                <button>Plano</button>
                                <button>+0,25</button>
                                <button>+0,50</button>
                                <button>+0,75</button>
                                <button>+1,00</button>
                                <button>+1,25</button>
                                <button>+1,50</button>
                                <button>+1,75</button>
                                <button>+2,00</button>
                                <button>+2,25</button>
                                <button>+2,50</button>
                                <button>+2,75</button>
                                <button>+3,00</button>
                                <button>+3,25</button>
                                <button>+3,50</button>
                                <button>+3,75</button>
                                <button>+4,00</button>
                                <button>+4,25</button>
                                <button>+4,50</button>
                                <button>+4,75</button>
                                <button>+5,00</button>
                                <button>+5,25</button>
                                <button>+5,50</button>
                                <button>+5,75</button>
                                <button>+6,00</button>
                                <button>+6,25</button>
                                <button>+6,50</button>
                                <button>+6,75</button>
                                <button>+7,00</button>
                                <button>+7,25</button>
                                <button>+7,50</button>
                                <button>+7,75</button>
                                <button>+8,00</button>
                                <button>+8,25</button>
                                <button>+8,50</button>
                                <button>+8,75</button>
                                <button>+9,00</button>
                                <button>+9,25</button>
                                <button>+9,50</button>
                                <button>+9,75</button>
                                <button>+10,00</button>
                                <button>+10,25</button>
                                <button>+10,50</button>
                                <button>+10,75</button>
                                <button>+11,00</button>
                                <button>+11,25</button>
                                <button>+11,50</button>
                                <button>+11,75</button>
                                <button>+12,00</button>
                                <button>+12,25</button>
                                <button>+12,50</button>
                                <button>+12,75</button>
                                <button>+13,00</button>
                                <button>+13,25</button>
                                <button>+13,50</button>
                                <button>+13,75</button>
                                <button>+14,00</button>
                                <button>+14,25</button>
                                <button>+14,50</button>
                                <button>+14,75</button>
                                <button>+15,00</button>
                                <button>+15,25</button>
                                <button>+15,50</button>
                                <button>+15,75</button>
                              </Select>
                            </ContainerSelect>
                          </ContainerGrauTop>
                        </Overlay>
                      )}
                    </ContainerDetails>
                  </ContainerInput>
                  <ContainerInput>
                    <ContainerDetails>
                      <Input />
                      <ContainerGrau>º</ContainerGrau>
                    </ContainerDetails>
                  </ContainerInput>
                  <ContainerInput>
                    <ContainerDetails>
                      <Input />
                      mm
                    </ContainerDetails>
                  </ContainerInput>
                </ContainerCalc>
              </ContainerDetailsImc>
            </ContainerPrescription>
          </ContainerDescription>
        </Label>
      </ContainerImc>
      <ContainerForm>
        <p>Observações</p>
        <RichText />
      </ContainerForm>
      <ContainerFormLentes>
        <p>Lentes</p>
        <ContainerInput>
          <form>
            <textarea></textarea>
          </form>
        </ContainerInput>
      </ContainerFormLentes>

      <ContainerButton>
        <button className="buttonOpen" onClick={handleOpenModalCheckBox}>
          Inserir lentes
        </button>
        <button className="buttonPrint">Imprimir Prescrição</button>
        {openModalCheckBox && (
          <>
            <Overlay>
              <ContainerModalCheckBox>
                <button
                  className="buttonClose"
                  onClick={handleCloseModalCheckBox}
                >
                  <Icon
                    name="closeSelect"
                    size={13}
                    style={{
                      marginTop: '2px'
                    }}
                  />
                </button>
                <ContainerText>
                  Selecione os items a serem inseridos em observações
                </ContainerText>
                <ContainerCheck>
                  <ContainerCheckBox>
                    <input type="checkbox" />
                    <label>Bifocais FLAT-TOP</label>
                  </ContainerCheckBox>
                  <ContainerCheckBox>
                    <input type="checkbox" />
                    <label>Anti reflexo</label>
                  </ContainerCheckBox>
                  <ContainerCheckBox>
                    <input type="checkbox" />
                    <label>Bifocais EXECUTIVE</label>
                  </ContainerCheckBox>
                  <ContainerCheckBox>
                    <input type="checkbox" />
                    <label>Bifocais MULT-SEG 45</label>
                  </ContainerCheckBox>
                  <ContainerCheckBox>
                    <input type="checkbox" />
                    <label>Bifocais ULTEX</label>
                  </ContainerCheckBox>
                  <ContainerCheckBox>
                    <input type="checkbox" />
                    <label>Bifocais NOLINE</label>
                  </ContainerCheckBox>
                </ContainerCheck>
                <ContainerButton>
                  <SaveAndAdd>Adicionar observações</SaveAndAdd>
                </ContainerButton>
              </ContainerModalCheckBox>
            </Overlay>
          </>
        )}
        {/* <hr
          style={{
            border: '1px dotted black',
            display: 'flex',
            width: '100%',
            marginTop: '15px'
          }}
        /> */}
      </ContainerButton>
    </Container>
  );
}
